### ISSUE TITLE
Internal Skill development

### ISSUE THREAD

**Issue by kianaditya** [CraftAcademyLabs/craft_con#3]
Do we need to talk about : 
* Systematic plan to keep coaches/staff updated in terms of relevant skills (apart from self-motivated learning)
* Managing internal knowledge/documenting knowledge we already have
* Staff attending meetups/workshops/seminars
* Certifications needed/recommended
* Adding incentives to motivate learning

**Comment by faraznaeem** [comment]
Questions added to personal development workshop
